
#include "test.h"
#include <stdio.h>

void test_di()
{
    int ret;
    printf("TEST d / i\n");
    printf("=====================================================\n");
    printf("flag : X / Width : X / precision : X\n");
    PRT(%d, DI);

    printf("=====================================================\n");
    printf("flag : X / Width : X / precision : number\n");
    PRT(%.d, 0);
    PRT(%.d, DI);
    PRT(%.0d, DI);
    PRT(%.1d, DI);
    PRT(%.2d, DI);
    PRT(%.3d, DI);
    PRT(%.4d, DI);
    PRT(%.5d, DI);
    PRT(%.6d, DI);
    // PRT(%.-1d, DI);

    printf("=====================================================\n");
    printf("flag : X / Width : X / precision : wildcard\n");
    PRT_W(%.*d, 0, DI);
    PRT_W(%.*d, -1, DI);
    PRT_W(%.*d, -2, DI);
    PRT_W(%.*d, -3, DI);
    PRT_W(%.*d, -4, DI);
    PRT_W(%.*d, -5, DI);
    PRT_W(%.*d, -6, DI);

    printf("=====================================================\n");
    printf("flag : X / Width : number / precision : X\n");
    PRT(%1d, DI);
    PRT(%2d, DI);
    PRT(%3d, DI);
    PRT(%4d, DI);
    PRT(%5d, DI);
    PRT(%6d, DI);

    printf("=====================================================\n");
    printf("flag : X / Width : number / precision : number\n");
    PRT(%2.d, DI);
    PRT(%2.0d, DI);
    PRT(%2.3d, DI);
    PRT(%2.4d, DI);
    PRT(%3.2d, DI);
    PRT(%3.3d, DI);
    PRT(%3.4d, DI);
    PRT(%4.3d, DI);
    PRT(%4.4d, DI);
    PRT(%4.5d, DI);

    printf("=====================================================\n");
    printf("flag : X / Width : number / precision : wildcard\n");
    PRT_W(%2.*d, 0, DI);
    PRT_W(%2.*d, 3, DI);
    PRT_W(%2.*d, 4, DI);
    PRT_W(%2.*d, -1, DI);
    PRT_W(%2.*d, -2, DI);
    PRT_W(%2.*d, -3, DI);
    PRT_W(%2.*d, -4, DI);
    PRT_W(%3.*d, 2, DI);
    PRT_W(%3.*d, 3, DI);
    PRT_W(%3.*d, 4, DI);
    PRT_W(%3.*d, -4, DI);
    PRT_W(%4.*d, 0, DI);
    PRT_W(%4.*d, -1, DI);
    PRT_W(%4.*d, 4, DI);
    PRT_W(%4.*d, 5, DI);
    PRT_W(%4.*d, -5, DI);

    printf("=====================================================\n");
    printf("flag : X / Width : wildcard / precision : X\n");
    PRT_W(%*d, 0, DI);
    PRT_W(%*d, 1, DI);
    PRT_W(%*d, 2, DI);
    PRT_W(%*d, 3, DI);
    PRT_W(%*d, 4, DI);
    PRT_W(%*d, 5, DI);
    PRT_W(%*d, 6, DI);
    PRT_W(%*d, -1, DI);
    PRT_W(%*d, -2, DI);
    PRT_W(%*d, -3, DI);
    PRT_W(%*d, -4, DI);
    PRT_W(%*d, -5, DI);
    PRT_W(%*d, -6, DI);

    printf("=====================================================\n");
    printf("flag : X / Width : wildcard / precision : number\n");
    PRT_W(%*.d, 0, DI);
    PRT_W(%*.0d, 1, DI);
    PRT_W(%*.4d, 2, DI);
    PRT_W(%*.1d, 3, DI);
    PRT_W(%*.5d, 4, DI);
    PRT_W(%*.1d, 5, DI);
    PRT_W(%*.6d, 6, DI);
    PRT_W(%*.0d, -1, DI);
    PRT_W(%*.4d, -2, DI);
    PRT_W(%*.3d, -3, DI);
    PRT_W(%*.3d, -4, DI);
    PRT_W(%*.3d, 4, DI);
    PRT_W(%*.5d, 3, DI);

    printf("=====================================================\n");
    printf("flag : X / Width : wildcard / precision : wildcard\n");
    PRT_WW(%*.*d, 0, 0, DI);
    PRT_WW(%*.*d, 1, 0, DI);
    PRT_WW(%*.*d, 2, 4, DI);
    PRT_WW(%*.*d, 3, 1, DI);
    PRT_WW(%*.*d, 4, 5, DI);
    PRT_WW(%*.*d, 5, 1, DI);
    PRT_WW(%*.*d, 6, 6, DI);
    PRT_WW(%*.*d, -1, 0, DI);
    PRT_WW(%*.*d, -2, 4, DI);
    PRT_WW(%*.*d, -3, 3, DI);
    PRT_WW(%*.*d, -4, 3, DI);
    PRT_WW(%*.*d, 4, 3, DI);
    PRT_WW(%*.*d, 3, 5, DI);
    PRT_WW(%*.*d, 2, -4, DI);
    PRT_WW(%*.*d, 3, -1, DI);
    PRT_WW(%*.*d, 4, -5, DI);
    PRT_WW(%*.*d, 5, -1, DI);
    PRT_WW(%*.*d, 6, -6, DI);

    printf("=====================================================\n");
    printf("flag : 0 / Width : X / precision : X\n");
    PRT(%0d, DI);

    printf("=====================================================\n");
    printf("flag : 0 / Width : X / precision : number\n");
    PRT(%0.d, DI);
    PRT(%0.0d, DI);
    PRT(%0.1d, DI);
    PRT(%0.2d, DI);
    PRT(%0.3d, DI);
    PRT(%0.4d, DI);
    PRT(%0.5d, DI);
    PRT(%0.6d, DI);

    printf("=====================================================\n");
    printf("flag : 0 / Width : X / precision : wildcard\n");
    PRT_W(%0.*d, 0, DI);
    PRT_W(%0.*d, 1, DI);
    PRT_W(%0.*d, 2, DI);
    PRT_W(%0.*d, 3, DI);
    PRT_W(%0.*d, 4, DI);
    PRT_W(%0.*d, 5, DI);
    PRT_W(%0.*d, 6, DI);
    PRT_W(%0.*d, -1, DI);
    PRT_W(%0.*d, -2, DI);
    PRT_W(%0.*d, -3, DI);
    PRT_W(%0.*d, -4, DI);
    PRT_W(%0.*d, -5, DI);
    PRT_W(%0.*d, -6, DI);

    printf("=====================================================\n");
    printf("flag : 0 / Width : number / precision : X\n");
    PRT(%01d, DI);
    PRT(%02d, DI);
    PRT(%03d, DI);
    PRT(%04d, DI);
    PRT(%05d, DI);
    PRT(%06d, DI);

    printf("=====================================================\n");
    printf("flag : 0 / Width : number / precision : number\n");
    PRT(%02.d, DI);
    PRT(%02.0d, DI);
    PRT(%02.3d, DI);
    PRT(%02.4d, DI);
    PRT(%03.2d, DI);
    PRT(%03.3d, DI);
    PRT(%03.4d, DI);
    PRT(%04.3d, DI);
    PRT(%04.4d, DI);
    PRT(%04.5d, DI);

    printf("=====================================================\n");
    printf("flag : 0 / Width : number / precision : wildcard\n");
    PRT_W(%02.*d, 0, DI);
    PRT_W(%02.*d, 3, DI);
    PRT_W(%02.*d, 4, DI);
    PRT_W(%02.*d, -1, DI);
    PRT_W(%02.*d, -2, DI);
    PRT_W(%02.*d, -3, DI);
    PRT_W(%02.*d, -4, DI);
    PRT_W(%03.*d, 2, DI);
    PRT_W(%03.*d, 3, DI);
    PRT_W(%03.*d, 4, DI);
    PRT_W(%03.*d, -4, DI);
    PRT_W(%04.*d, 0, DI);
    PRT_W(%04.*d, -1, DI);
    PRT_W(%04.*d, 4, DI);
    PRT_W(%04.*d, 5, DI);
    PRT_W(%04.*d, -5, DI);

    printf("=====================================================\n");
    printf("flag : 0 / Width : wildcard / precision : X\n");
    PRT_W(%0*d, 0, DI);
    PRT_W(%0*d, 1, DI);
    PRT_W(%0*d, 2, DI);
    PRT_W(%0*d, 3, DI);
    PRT_W(%0*d, 4, DI);
    PRT_W(%0*d, 5, DI);
    PRT_W(%0*d, 6, DI);
    PRT_W(%0*d, -1, DI);
    PRT_W(%0*d, -2, DI);
    PRT_W(%0*d, -3, DI);
    PRT_W(%0*d, -4, DI);
    PRT_W(%0*d, -5, DI);
    PRT_W(%0*d, -6, DI);

    printf("=====================================================\n");
    printf("flag : 0 / Width : wildcard / precision : number\n");
    PRT_W(%0*.d, 0, DI);
    PRT_W(%0*.0d, 1, DI);
    PRT_W(%0*.4d, 2, DI);
    PRT_W(%0*.1d, 3, DI);
    PRT_W(%0*.5d, 4, DI);
    PRT_W(%0*.1d, 5, DI);
    PRT_W(%0*.6d, 6, DI);
    PRT_W(%0*.0d, -1, DI);
    PRT_W(%0*.4d, -2, DI);
    PRT_W(%0*.3d, -3, DI);
    PRT_W(%0*.3d, -4, DI);
    PRT_W(%0*.3d, 4, DI);
    PRT_W(%0*.5d, 3, DI);

    printf("=====================================================\n");
    printf("flag : 0 / Width : wildcard / precision : wildcard\n");
    PRT_WW(%0*.*d, 0, 0, DI);
    PRT_WW(%0*.*d, 1, 0, DI);
    PRT_WW(%0*.*d, 2, 4, DI);
    PRT_WW(%0*.*d, 3, 1, DI);
    PRT_WW(%0*.*d, 4, 5, DI);
    PRT_WW(%0*.*d, 5, 1, DI);
    PRT_WW(%0*.*d, 6, 6, DI);
    PRT_WW(%0*.*d, -1, 0, DI);
    PRT_WW(%0*.*d, -2, 4, DI);
    PRT_WW(%0*.*d, -3, 3, DI);
    PRT_WW(%0*.*d, -4, 3, DI);
    PRT_WW(%0*.*d, 4, 3, DI);
    PRT_WW(%0*.*d, 3, 5, DI);
    PRT_WW(%0*.*d, 2, -4, DI);
    PRT_WW(%0*.*d, 3, -1, DI);
    PRT_WW(%0*.*d, 4, -5, DI);
    PRT_WW(%0*.*d, 5, -1, DI);
    PRT_WW(%0*.*d, 6, -6, DI);
    PRT_WW(%0*.*d, -6, -6, DI);

    printf("=====================================================\n");
    printf("flag : - / Width : X / precision : X\n");
    PRT(%-d, DI);

    printf("=====================================================\n");
    printf("flag : - / Width : X / precision : number\n");
    PRT(%-.d, DI);
    PRT(%-.0d, DI);
    PRT(%-.1d, DI);
    PRT(%-.2d, DI);
    PRT(%-.3d, DI);
    PRT(%-.4d, DI);
    PRT(%-.5d, DI);
    PRT(%-.6d, DI);

    printf("=====================================================\n");
    printf("flag : - / Width : X / precision : wildcard\n");
    PRT_W(%-.*d, 0, DI);
    PRT_W(%-.*d, 1, DI);
    PRT_W(%-.*d, 2, DI);
    PRT_W(%-.*d, 3, DI);
    PRT_W(%-.*d, 4, DI);
    PRT_W(%-.*d, 5, DI);
    PRT_W(%-.*d, 6, DI);
    PRT_W(%-.*d, -1, DI);
    PRT_W(%-.*d, -2, DI);
    PRT_W(%-.*d, -3, DI);
    PRT_W(%-.*d, -4, DI);
    PRT_W(%-.*d, -5, DI);
    PRT_W(%-.*d, -6, DI);

    printf("=====================================================\n");
    printf("flag : - / Width : number / precision : X\n");
    // PRT(%-0d, DI);
    PRT(%-1d, DI);
    PRT(%-2d, DI);
    PRT(%-3d, DI);
    PRT(%-4d, DI);
    PRT(%-5d, DI);
    PRT(%-6d, DI);

    printf("=====================================================\n");
    printf("flag : - / Width : number / precision : number\n");
    PRT(%-2.d, DI);
    PRT(%-2.0d, DI);
    PRT(%-2.3d, DI);
    PRT(%-2.4d, DI);
    PRT(%-3.2d, DI);
    PRT(%-3.3d, DI);
    PRT(%-3.4d, DI);
    PRT(%-4.3d, DI);
    PRT(%-4.4d, DI);
    PRT(%-4.5d, DI);

    printf("=====================================================\n");
    printf("flag : - / Width : number / precision : wildcard\n");
    PRT_W(%-2.*d, 0, DI);
    PRT_W(%-2.*d, 3, DI);
    PRT_W(%-2.*d, 4, DI);
    PRT_W(%-2.*d, -1, DI);
    PRT_W(%-2.*d, -2, DI);
    PRT_W(%-2.*d, -3, DI);
    PRT_W(%-2.*d, -4, DI);
    PRT_W(%-3.*d, 2, DI);
    PRT_W(%-3.*d, 3, DI);
    PRT_W(%-3.*d, 4, DI);
    PRT_W(%-3.*d, -4, DI);
    PRT_W(%-4.*d, 0, DI);
    PRT_W(%-4.*d, -1, DI);
    PRT_W(%-4.*d, 4, DI);
    PRT_W(%-4.*d, 5, DI);
    PRT_W(%-4.*d, -5, DI);

    printf("=====================================================\n");
    printf("flag : - / Width : wildcard / precision : X\n");
    PRT_W(%-*d, 0, DI);
    PRT_W(%-*d, 1, DI);
    PRT_W(%-*d, 2, DI);
    PRT_W(%-*d, 3, DI);
    PRT_W(%-*d, 4, DI);
    PRT_W(%-*d, 5, DI);
    PRT_W(%-*d, 6, DI);
    PRT_W(%-*d, -1, DI);
    PRT_W(%-*d, -2, DI);
    PRT_W(%-*d, -3, DI);
    PRT_W(%-*d, -4, DI);
    PRT_W(%-*d, -5, DI);
    PRT_W(%-*d, -6, DI);

    printf("=====================================================\n");
    printf("flag : - / Width : wildcard / precision : number\n");
    PRT_W(%-*.d, 0, DI);
    PRT_W(%-*.0d, 1, DI);
    PRT_W(%-*.4d, 2, DI);
    PRT_W(%-*.1d, 3, DI);
    PRT_W(%-*.5d, 4, DI);
    PRT_W(%-*.1d, 5, DI);
    PRT_W(%-*.6d, 6, DI);
    PRT_W(%-*.0d, -1, DI);
    PRT_W(%-*.4d, -2, DI);
    PRT_W(%-*.3d, -3, DI);
    PRT_W(%-*.3d, -4, DI);
    PRT_W(%-*.3d, 4, DI);
    PRT_W(%-*.5d, 3, DI);

    printf("=====================================================\n");
    printf("flag : - / Width : wildcard / precision : wildcard\n");
    PRT_WW(%-*.*d, 0, 0, DI);
    PRT_WW(%-*.*d, 1, 0, DI);
    PRT_WW(%-*.*d, 2, 4, DI);
    PRT_WW(%-*.*d, 3, 1, DI);
    PRT_WW(%-*.*d, 4, 5, DI);
    PRT_WW(%-*.*d, 5, 1, DI);
    PRT_WW(%-*.*d, 6, 6, DI);
    PRT_WW(%-*.*d, -1, 0, DI);
    PRT_WW(%-*.*d, -2, 4, DI);
    PRT_WW(%-*.*d, -3, 3, DI);
    PRT_WW(%-*.*d, -4, 3, DI);
    PRT_WW(%-*.*d, 4, 3, DI);
    PRT_WW(%-*.*d, 3, 5, DI);
    PRT_WW(%-*.*d, 2, -4, DI);
    PRT_WW(%-*.*d, 3, -1, DI);
    PRT_WW(%-*.*d, 4, -5, DI);
    PRT_WW(%-*.*d, 5, -1, DI);
    PRT_WW(%-*.*d, 6, -6, DI);
    printf("=====================================================\n");
}
