#include "test.h"
#include <stdio.h>


void test_s(char *str)
{
    int ret;
    printf("TEST s\n");
    printf("=====================================================\n");
    printf("flag : X / Width : X / precision : X\n");
    PRT(%s, str);

    printf("=====================================================\n");
    printf("flag : X / Width : X / precision : number\n");
    PRT(%.s, str);
    PRT(%.1s, str);
    PRT(%.2s, str);
    PRT(%.3s, str);
    PRT(%.4s, str);
    PRT(%.5s, str);
    PRT(%.6s, str);
    // PRT(%.-1s, str);

    printf("=====================================================\n");
    printf("flag : X / Width : X / precision : wildcard\n");
    PRT_W(%.*s, 0, str);
    PRT_W(%.*s, 1, str);
    PRT_W(%.*s, 2, str);
    PRT_W(%.*s, 3, str);
    PRT_W(%.*s, 4, str);
    PRT_W(%.*s, 5, str);
    PRT_W(%.*s, 6, str);

    PRT_W(%.*s, -1, str);
    PRT_W(%.*s, -2, str);
    PRT_W(%.*s, -3, str);
    PRT_W(%.*s, -4, str);
    PRT_W(%.*s, -5, str);
    PRT_W(%.*s, -6, str);

    printf("=====================================================\n");
    printf("flag : X / Width : number / precision : X\n");
    PRT(%1s, str);
    PRT(%2s, str);
    PRT(%3s, str);
    PRT(%4s, str);
    PRT(%5s, str);
    PRT(%6s, str);

    printf("=====================================================\n");
    printf("flag : X / Width : number / precision : number\n");
    PRT(%1.s, str);
    PRT(%1.0s, str);
    PRT(%1.3s, str);
    PRT(%1.4s, str);
	PRT(%1.5s, str);
	PRT(%1.6s, str);

	PRT(%2.s, str);
    PRT(%2.0s, str);
    PRT(%2.1s, str);
    PRT(%2.2s, str);
    PRT(%2.3s, str);
    PRT(%2.4s, str);
    PRT(%2.5s, str);
    PRT(%2.6s, str);

    PRT(%3.2s, str);
    PRT(%3.3s, str);
    PRT(%3.4s, str);
	PRT(%4.2s, str);
    PRT(%4.3s, str);
    PRT(%4.4s, str);
    PRT(%4.5s, str);
	PRT(%4.6s, str);

    printf("=====================================================\n");
    printf("flag : X / Width : number / precision : wildcard\n");
    PRT_W(%2.*s, 0, str);
    PRT_W(%2.*s, 3, str);
    PRT_W(%2.*s, 4, str);
    PRT_W(%2.*s, -1, str);
    PRT_W(%2.*s, -2, str);
    PRT_W(%2.*s, -3, str);
    PRT_W(%2.*s, -4, str);
    PRT_W(%3.*s, 2, str);
    PRT_W(%3.*s, 3, str);
    PRT_W(%3.*s, 4, str);
    PRT_W(%3.*s, -4, str);
    PRT_W(%4.*s, 0, str);
    PRT_W(%4.*s, -1, str);
    PRT_W(%4.*s, 4, str);
    PRT_W(%4.*s, 5, str);
    PRT_W(%4.*s, -5, str);

    printf("=====================================================\n");
    printf("flag : X / Width : wildcard / precision : X\n");
    PRT_W(%*s, 0, str);
    PRT_W(%*s, 1, str);
    PRT_W(%*s, 2, str);
    PRT_W(%*s, 3, str);
    PRT_W(%*s, 4, str);
    PRT_W(%*s, 5, str);
    PRT_W(%*s, 6, str);
    PRT_W(%*s, -1, str);
    PRT_W(%*s, -2, str);
    PRT_W(%*s, -3, str);
    PRT_W(%*s, -4, str);
    PRT_W(%*s, -5, str);
    PRT_W(%*s, -6, str);

    printf("=====================================================\n");
    printf("flag : X / Width : wildcard / precision : number\n");
    PRT_W(%*.s, 0, str);
    PRT_W(%*.0s, 1, str);
    PRT_W(%*.4s, 2, str);
    PRT_W(%*.1s, 3, str);
    PRT_W(%*.5s, 4, str);
    PRT_W(%*.1s, 5, str);
    PRT_W(%*.6s, 6, str);
    PRT_W(%*.0s, -1, str);
    PRT_W(%*.4s, -2, str);
    PRT_W(%*.3s, -3, str);
    PRT_W(%*.3s, -4, str);
    PRT_W(%*.3s, 4, str);
    PRT_W(%*.5s, 3, str);

    printf("=====================================================\n");
    printf("flag : X / Width : wildcard / precision : wildcard\n");
    PRT_WW(%*.*s, 0, 0, str);
    PRT_WW(%*.*s, 1, 0, str);
    PRT_WW(%*.*s, 2, 4, str);
    PRT_WW(%*.*s, 3, 1, str);
    PRT_WW(%*.*s, 4, 5, str);
    PRT_WW(%*.*s, 5, 1, str);
    PRT_WW(%*.*s, 6, 6, str);
    PRT_WW(%*.*s, -1, 0, str);
    PRT_WW(%*.*s, -2, 4, str);
    PRT_WW(%*.*s, -3, 3, str);
    PRT_WW(%*.*s, -4, 3, str);
    PRT_WW(%*.*s, 4, 3, str);
    PRT_WW(%*.*s, 3, 5, str);
    PRT_WW(%*.*s, 2, -4, str);
    PRT_WW(%*.*s, 3, -1, str);
    PRT_WW(%*.*s, 4, -5, str);
    PRT_WW(%*.*s, 5, -1, str);
    PRT_WW(%*.*s, 6, -6, str);
    PRT_WW(%*.*s, -6, -6, str);

    printf("=====================================================\n");
    printf("flag : 0 / Width : X / precision : X\n");
    printf("undefined behavier\n");
    // PRT(%0s, str);

    printf("=====================================================\n");
    printf("flag : 0 / Width : X / precision : number\n");
    printf("undefined behavier\n");
    // PRT(%0.s, str);
    // PRT(%0.1s, str);
    // PRT(%0.2s, str);
    // PRT(%0.3s, str);
    // PRT(%0.4s, str);
    // PRT(%0.5s, str);
    // PRT(%0.6s, str);

    printf("=====================================================\n");
    printf("flag : 0 / Width : X / precision : wildcard\n");
    printf("undefined behavier\n");
    // PRT_W(%0.*s, 0, str);
    // PRT_W(%0.*s, 1, str);
    // PRT_W(%0.*s, 2, str);
    // PRT_W(%0.*s, 3, str);
    // PRT_W(%0.*s, 4, str);
    // PRT_W(%0.*s, 5, str);
    // PRT_W(%0.*s, 6, str);
    // PRT_W(%0.*s, -1, str);
    // PRT_W(%0.*s, -2, str);
    // PRT_W(%0.*s, -3, str);
    // PRT_W(%0.*s, -4, str);
    // PRT_W(%0.*s, -5, str);
    // PRT_W(%0.*s, -6, str);

    printf("=====================================================\n");
    printf("flag : 0 / Width : number / precision : X\n");
    printf("undefined behavier\n");
    // PRT(%01s, str);
    // PRT(%02s, str);
    // PRT(%03s, str);
    // PRT(%04s, str);
    // PRT(%05s, str);
    // PRT(%06s, str);

    printf("=====================================================\n");
    printf("flag : 0 / Width : number / precision : number\n");
    printf("undefined behavier\n");
    // PRT(%02.s, str);
    // PRT(%02.0s, str);
    // PRT(%02.3s, str);
    // PRT(%02.4s, str);
    // PRT(%03.2s, str);
    // PRT(%03.3s, str);
    // PRT(%03.4s, str);
    // PRT(%04.3s, str);
    // PRT(%04.4s, str);
    // PRT(%04.5s, str);

    printf("=====================================================\n");
    printf("flag : 0 / Width : number / precision : wildcard\n");
    printf("undefined behavier\n");
    // PRT_W(%02.*s, 0, str);
    // PRT_W(%02.*s, 3, str);
    // PRT_W(%02.*s, 4, str);
    // PRT_W(%02.*s, -1, str);
    // PRT_W(%02.*s, -2, str);
    // PRT_W(%02.*s, -3, str);
    // PRT_W(%02.*s, -4, str);
    // PRT_W(%03.*s, 2, str);
    // PRT_W(%03.*s, 3, str);
    // PRT_W(%03.*s, 4, str);
    // PRT_W(%03.*s, -4, str);
    // PRT_W(%04.*s, 0, str);
    // PRT_W(%04.*s, -1, str);
    // PRT_W(%04.*s, 4, str);
    // PRT_W(%04.*s, 5, str);
    // PRT_W(%04.*s, -5, str);

    printf("=====================================================\n");
    printf("flag : 0 / Width : wildcard / precision : X\n");
    printf("undefined behavier\n");
    // PRT_W(%0*s, 0, str);
    // PRT_W(%0*s, 1, str);
    // PRT_W(%0*s, 2, str);
    // PRT_W(%0*s, 3, str);
    // PRT_W(%0*s, 4, str);
    // PRT_W(%0*s, 5, str);
    // PRT_W(%0*s, 6, str);
    // PRT_W(%0*s, -1, str);
    // PRT_W(%0*s, -2, str);
    // PRT_W(%0*s, -3, str);
    // PRT_W(%0*s, -4, str);
    // PRT_W(%0*s, -5, str);
    // PRT_W(%0*s, -6, str);

    printf("=====================================================\n");
    printf("flag : 0 / Width : wildcard / precision : number\n");
    printf("undefined behavier\n");
    // PRT_W(%0*.s, 0, str);
    // PRT_W(%0*.0s, 1, str);
    // PRT_W(%0*.4s, 2, str);
    // PRT_W(%0*.1s, 3, str);
    // PRT_W(%0*.5s, 4, str);
    // PRT_W(%0*.1s, 5, str);
    // PRT_W(%0*.6s, 6, str);
    // PRT_W(%0*.0s, -1, str);
    // PRT_W(%0*.4s, -2, str);
    // PRT_W(%0*.3s, -3, str);
    // PRT_W(%0*.3s, -4, str);
    // PRT_W(%0*.3s, 4, str);
    // PRT_W(%0*.5s, 3, str);

    printf("=====================================================\n");
    printf("flag : 0 / Width : wildcard / precision : wildcard\n");
    printf("undefined behavier\n");
    // PRT_WW(%0*.*s, 0, 0, str);
    // PRT_WW(%0*.*s, 1, 0, str);
    // PRT_WW(%0*.*s, 2, 4, str);
    // PRT_WW(%0*.*s, 3, 1, str);
    // PRT_WW(%0*.*s, 4, 5, str);
    // PRT_WW(%0*.*s, 5, 1, str);
    // PRT_WW(%0*.*s, 6, 6, str);
    // PRT_WW(%0*.*s, -1, 0, str);
    // PRT_WW(%0*.*s, -2, 4, str);
    // PRT_WW(%0*.*s, -3, 3, str);
    // PRT_WW(%0*.*s, -4, 3, str);
    // PRT_WW(%0*.*s, 4, 3, str);
    // PRT_WW(%0*.*s, 3, 5, str);
    // PRT_WW(%0*.*s, 2, -4, str);
    // PRT_WW(%0*.*s, 3, -1, str);
    // PRT_WW(%0*.*s, 4, -5, str);
    // PRT_WW(%0*.*s, 5, -1, str);
    // PRT_WW(%0*.*s, 6, -6, str);

    printf("=====================================================\n");
    printf("flag : - / Width : X / precision : X\n");
    PRT(%-s, str);

    printf("=====================================================\n");
    printf("flag : - / Width : X / precision : number\n");
    PRT(%-.s, str);
    PRT(%-.0s, str);
    PRT(%-.1s, str);
    PRT(%-.2s, str);
    PRT(%-.3s, str);
    PRT(%-.4s, str);
    PRT(%-.5s, str);
    PRT(%-.6s, str);

    printf("=====================================================\n");
    printf("flag : - / Width : X / precision : wildcard\n");
    PRT_W(%-.*s, 0, str);
    PRT_W(%-.*s, 1, str);
    PRT_W(%-.*s, 2, str);
    PRT_W(%-.*s, 3, str);
    PRT_W(%-.*s, 4, str);
    PRT_W(%-.*s, 5, str);
    PRT_W(%-.*s, 6, str);
    PRT_W(%-.*s, -1, str);
    PRT_W(%-.*s, -2, str);
    PRT_W(%-.*s, -3, str);
    PRT_W(%-.*s, -4, str);
    PRT_W(%-.*s, -5, str);
    PRT_W(%-.*s, -6, str);

    printf("=====================================================\n");
    printf("flag : - / Width : number / precision : X\n");
    // PRT(%-0s, str);
    PRT(%-1s, str);
    PRT(%-2s, str);
    PRT(%-3s, str);
    PRT(%-4s, str);
    PRT(%-5s, str);
    PRT(%-6s, str);

    printf("=====================================================\n");
    printf("flag : - / Width : number / precision : number\n");
    PRT(%-2.s, str);
    PRT(%-2.0s, str);
    PRT(%-2.3s, str);
    PRT(%-2.4s, str);
    PRT(%-3.2s, str);
    PRT(%-3.3s, str);
    PRT(%-3.4s, str);
    PRT(%-4.3s, str);
    PRT(%-4.4s, str);
    PRT(%-4.5s, str);

    printf("=====================================================\n");
    printf("flag : - / Width : number / precision : wildcard\n");
    PRT_W(%-2.*s, 0, str);
    PRT_W(%-2.*s, 3, str);
    PRT_W(%-2.*s, 4, str);
    PRT_W(%-2.*s, -1, str);
    PRT_W(%-2.*s, -2, str);
    PRT_W(%-2.*s, -3, str);
    PRT_W(%-2.*s, -4, str);
    PRT_W(%-3.*s, 2, str);
    PRT_W(%-3.*s, 3, str);
    PRT_W(%-3.*s, 4, str);
    PRT_W(%-3.*s, -4, str);
    PRT_W(%-4.*s, 0, str);
    PRT_W(%-4.*s, -1, str);
    PRT_W(%-4.*s, 4, str);
    PRT_W(%-4.*s, 5, str);
    PRT_W(%-4.*s, -5, str);

    printf("=====================================================\n");
    printf("flag : - / Width : wildcard / precision : X\n");
    PRT_W(%-*s, 0, str);
    PRT_W(%-*s, 1, str);
    PRT_W(%-*s, 2, str);
    PRT_W(%-*s, 3, str);
    PRT_W(%-*s, 4, str);
    PRT_W(%-*s, 5, str);
    PRT_W(%-*s, 6, str);
    PRT_W(%-*s, -1, str);
    PRT_W(%-*s, -2, str);
    PRT_W(%-*s, -3, str);
    PRT_W(%-*s, -4, str);
    PRT_W(%-*s, -5, str);
    PRT_W(%-*s, -6, str);

    printf("=====================================================\n");
    printf("flag : - / Width : wildcard / precision : number\n");
    PRT_W(%-*.s, 0, str);
    PRT_W(%-*.0s, 1, str);
    PRT_W(%-*.4s, 2, str);
    PRT_W(%-*.1s, 3, str);
    PRT_W(%-*.5s, 4, str);
    PRT_W(%-*.1s, 5, str);
    PRT_W(%-*.6s, 6, str);
    PRT_W(%-*.0s, -1, str);
    PRT_W(%-*.4s, -2, str);
    PRT_W(%-*.3s, -3, str);
    PRT_W(%-*.3s, -4, str);
    PRT_W(%-*.3s, 4, str);
    PRT_W(%-*.5s, 3, str);

    printf("=====================================================\n");
    printf("flag : - / Width : wildcard / precision : wildcard\n");
    PRT_WW(%-*.*s, 0, 0, str);
    PRT_WW(%-*.*s, 1, 0, str);
    PRT_WW(%-*.*s, 2, 4, str);
    PRT_WW(%-*.*s, 3, 1, str);
    PRT_WW(%-*.*s, 4, 5, str);
    PRT_WW(%-*.*s, 5, 1, str);
    PRT_WW(%-*.*s, 6, 6, str);
    PRT_WW(%-*.*s, -1, 0, str);
    PRT_WW(%-*.*s, -2, 4, str);
    PRT_WW(%-*.*s, -3, 3, str);
    PRT_WW(%-*.*s, -4, 3, str);
    PRT_WW(%-*.*s, 4, 3, str);
    PRT_WW(%-*.*s, 3, 5, str);
    PRT_WW(%-*.*s, 2, -4, str);
    PRT_WW(%-*.*s, 3, -1, str);
    PRT_WW(%-*.*s, 4, -5, str);
    PRT_WW(%-*.*s, 5, -1, str);
    PRT_WW(%-*.*s, 6, -6, str);
    printf("=====================================================\n");
}
