#include "test.h"
#include <stdio.h>

void test_c()
{
    int ret;
    printf("TEST c\n");
    printf("=====================================================\n");
    printf("flag : X / Width : X / precision : X\n");
    PRT(%c, C);

    printf("=====================================================\n");
    printf("flag : X / Width : X / precision : number\n");
    PRT(%.c, C);     //mac available
    // PRT(%.1c, C);
    // PRT(%.2c, C);
    // PRT(%.3c, C);
    // PRT(%.4c, C);
    // PRT(%.5c, C);
    // PRT(%.6c, C);
    // PRT(%.-1c, C);

    printf("=====================================================\n");
    printf("flag : X / Width : X / precision : wildcard\n");
    printf("undefined behavier\n");
    // PRT_W(%.*c, 0, C);
    // PRT_W(%.*c, -1, C);
    // PRT_W(%.*c, -2, C);
    // PRT_W(%.*c, -3, C);
    // PRT_W(%.*c, -4, C);
    // PRT_W(%.*c, -5, C);
    // PRT_W(%.*c, -6, C);

    printf("=====================================================\n");
    printf("flag : X / Width : number / precision : X\n");
    PRT(%1c, C);
    PRT(%2c, C);
    PRT(%3c, C);
    PRT(%4c, C);
    PRT(%5c, C);
    PRT(%6c, C);

    printf("=====================================================\n");
    printf("flag : X / Width : number / precision : number\n");
    PRT(%2.c, C);
    // PRT(%2.0c, C);
    // PRT(%2.3c, C);
    // PRT(%2.4c, C);
    // PRT(%3.2c, C);
    // PRT(%3.3c, C);
    // PRT(%3.4c, C);
    // PRT(%4.3c, C);
    // PRT(%4.4c, C);
    // PRT(%4.5c, C);

    printf("=====================================================\n");
    printf("flag : X / Width : number / precision : wildcard\n");
    printf("undefined behavier\n");
    // PRT_W(%2.*c, 0, C);
    // PRT_W(%2.*c, 3, C);
    // PRT_W(%2.*c, 4, C);
    // PRT_W(%2.*c, -1, C);
    // PRT_W(%2.*c, -2, C);
    // PRT_W(%2.*c, -3, C);
    // PRT_W(%2.*c, -4, C);
    // PRT_W(%3.*c, 2, C);
    // PRT_W(%3.*c, 3, C);
    // PRT_W(%3.*c, 4, C);
    // PRT_W(%3.*c, -4, C);
    // PRT_W(%4.*c, 0, C);
    // PRT_W(%4.*c, -1, C);
    // PRT_W(%4.*c, 4, C);
    // PRT_W(%4.*c, 5, C);
    // PRT_W(%4.*c, -5, C);

    printf("=====================================================\n");
    printf("flag : X / Width : wildcard / precision : X\n");
    PRT_W(%*c, 0, C);
    PRT_W(%*c, 1, C);
    PRT_W(%*c, 2, C);
    PRT_W(%*c, 3, C);
    PRT_W(%*c, 4, C);
    PRT_W(%*c, 5, C);
    PRT_W(%*c, 6, C);
    PRT_W(%*c, -1, C);
    PRT_W(%*c, -2, C);
    PRT_W(%*c, -3, C);
    PRT_W(%*c, -4, C);
    PRT_W(%*c, -5, C);
    PRT_W(%*c, -6, C);

    printf("=====================================================\n");
    printf("flag : X / Width : wildcard / precision : number\n");
    PRT_W(%*.c, 0, C);
    // PRT_W(%*.0c, 1, C);
    // PRT_W(%*.4c, 2, C);
    // PRT_W(%*.1c, 3, C);
    // PRT_W(%*.5c, 4, C);
    // PRT_W(%*.1c, 5, C);
    // PRT_W(%*.6c, 6, C);
    // PRT_W(%*.0c, -1, C);
    // PRT_W(%*.4c, -2, C);
    // PRT_W(%*.3c, -3, C);
    // PRT_W(%*.3c, -4, C);
    // PRT_W(%*.3c, 4, C);
    // PRT_W(%*.5c, 3, C);

    printf("=====================================================\n");
    printf("flag : X / Width : wildcard / precision : wildcard\n");
    printf("undefined behavier\n");
    // PRT_WW(%*.*c, 0, 0, C);
    // PRT_WW(%*.*c, 1, 0, C);
    // PRT_WW(%*.*c, 2, 4, C);
    // PRT_WW(%*.*c, 3, 1, C);
    // PRT_WW(%*.*c, 4, 5, C);
    // PRT_WW(%*.*c, 5, 1, C);
    // PRT_WW(%*.*c, 6, 6, C);
    // PRT_WW(%*.*c, -1, 0, C);
    // PRT_WW(%*.*c, -2, 4, C);
    // PRT_WW(%*.*c, -3, 3, C);
    // PRT_WW(%*.*c, -4, 3, C);
    // PRT_WW(%*.*c, 4, 3, C);
    // PRT_WW(%*.*c, 3, 5, C);
    // PRT_WW(%*.*c, 2, -4, C);
    // PRT_WW(%*.*c, 3, -1, C);
    // PRT_WW(%*.*c, 4, -5, C);
    // PRT_WW(%*.*c, 5, -1, C);
    // PRT_WW(%*.*c, 6, -6, C);

    printf("=====================================================\n");
    printf("flag : 0 / Width : X / precision : X\n");
    printf("undefined behavier\n");
    // PRT(%0c, C);
    printf("=====================================================\n");
    printf("flag : 0 / Width : X / precision : number\n");
    printf("undefined behavier\n");
    // PRT(%0.c, C);
    // PRT(%0.1c, C);
    // PRT(%0.2c, C);
    // PRT(%0.3c, C);
    // PRT(%0.4c, C);
    // PRT(%0.5c, C);
    // PRT(%0.6c, C);
    printf("=====================================================\n");
    printf("flag : 0 / Width : X / precision : wildcard\n");
    printf("undefined behavier\n");
    // PRT_W(%0.*c, 0, C);
    // PRT_W(%0.*c, 1, C);
    // PRT_W(%0.*c, 2, C);
    // PRT_W(%0.*c, 3, C);
    // PRT_W(%0.*c, 4, C);
    // PRT_W(%0.*c, 5, C);
    // PRT_W(%0.*c, 6, C);
    // PRT_W(%0.*c, -1, C);
    // PRT_W(%0.*c, -2, C);
    // PRT_W(%0.*c, -3, C);
    // PRT_W(%0.*c, -4, C);
    // PRT_W(%0.*c, -5, C);
    // PRT_W(%0.*c, -6, C);
    printf("=====================================================\n");
    printf("flag : 0 / Width : number / precision : X\n");
    printf("undefined behavier\n");
    // PRT(%01c, C);
    // PRT(%02c, C);
    // PRT(%03c, C);
    // PRT(%04c, C);
    // PRT(%05c, C);
    // PRT(%06c, C);
    printf("=====================================================\n");
    printf("flag : 0 / Width : number / precision : number\n");
    printf("undefined behavier\n");
    // PRT(%02.0c, C);
    // PRT(%02.3c, C);
    // PRT(%02.4c, C);
    // PRT(%03.2c, C);
    // PRT(%03.3c, C);
    // PRT(%03.4c, C);
    // PRT(%04.3c, C);
    // PRT(%04.4c, C);
    // PRT(%04.5c, C);

    printf("=====================================================\n");
    printf("flag : 0 / Width : number / precision : wildcard\n");
    printf("undefined behavier\n");
    // PRT_W(%02.*c, 0, C);
    // PRT_W(%02.*c, 3, C);
    // PRT_W(%02.*c, 4, C);
    // PRT_W(%02.*c, -1, C);
    // PRT_W(%02.*c, -2, C);
    // PRT_W(%02.*c, -3, C);
    // PRT_W(%02.*c, -4, C);
    // PRT_W(%03.*c, 2, C);
    // PRT_W(%03.*c, 3, C);
    // PRT_W(%03.*c, 4, C);
    // PRT_W(%03.*c, -4, C);
    // PRT_W(%04.*c, 0, C);
    // PRT_W(%04.*c, -1, C);
    // PRT_W(%04.*c, 4, C);
    // PRT_W(%04.*c, 5, C);
    // PRT_W(%04.*c, -5, C);

    printf("=====================================================\n");
    printf("flag : 0 / Width : wildcard / precision : X\n");
    printf("undefined behavier\n");
    // PRT_W(%0*c, 0, C);
    // PRT_W(%0*c, 1, C);
    // PRT_W(%0*c, 2, C);
    // PRT_W(%0*c, 3, C);
    // PRT_W(%0*c, 4, C);
    // PRT_W(%0*c, 5, C);
    // PRT_W(%0*c, 6, C);
    // PRT_W(%0*c, -1, C);
    // PRT_W(%0*c, -2, C);
    // PRT_W(%0*c, -3, C);
    // PRT_W(%0*c, -4, C);
    // PRT_W(%0*c, -5, C);
    // PRT_W(%0*c, -6, C);

    printf("=====================================================\n");
    printf("flag : 0 / Width : wildcard / precision : number\n");
    printf("undefined behavier\n");
    // PRT_W(%0*.c, 0, C);
    // PRT_W(%0*.0c, 1, C);
    // PRT_W(%0*.4c, 2, C);
    // PRT_W(%0*.1c, 3, C);
    // PRT_W(%0*.5c, 4, C);
    // PRT_W(%0*.1c, 5, C);
    // PRT_W(%0*.6c, 6, C);
    // PRT_W(%0*.0c, -1, C);
    // PRT_W(%0*.4c, -2, C);
    // PRT_W(%0*.3c, -3, C);
    // PRT_W(%0*.3c, -4, C);
    // PRT_W(%0*.3c, 4, C);
    // PRT_W(%0*.5c, 3, C);

    printf("=====================================================\n");
    printf("flag : 0 / Width : wildcard / precision : wildcard\n");
    printf("undefined behavier\n");
    // PRT_WW(%0*.*c, 0, 0, C);
    // PRT_WW(%0*.*c, 1, 0, C);
    // PRT_WW(%0*.*c, 2, 4, C);
    // PRT_WW(%0*.*c, 3, 1, C);
    // PRT_WW(%0*.*c, 4, 5, C);
    // PRT_WW(%0*.*c, 5, 1, C);
    // PRT_WW(%0*.*c, 6, 6, C);
    // PRT_WW(%0*.*c, -1, 0, C);
    // PRT_WW(%0*.*c, -2, 4, C);
    // PRT_WW(%0*.*c, -3, 3, C);
    // PRT_WW(%0*.*c, -4, 3, C);
    // PRT_WW(%0*.*c, 4, 3, C);
    // PRT_WW(%0*.*c, 3, 5, C);
    // PRT_WW(%0*.*c, 2, -4, C);
    // PRT_WW(%0*.*c, 3, -1, C);
    // PRT_WW(%0*.*c, 4, -5, C);
    // PRT_WW(%0*.*c, 5, -1, C);
    // PRT_WW(%0*.*c, 6, -6, C);

    printf("=====================================================\n");
    printf("flag : - / Width : X / precision : X\n");
    PRT(%-c, C);
    printf("=====================================================\n");
    printf("flag : - / Width : X / precision : number\n");
    PRT(%-.c, C);
    // PRT(%-.0c, C);
    // PRT(%-.1c, C);
    // PRT(%-.2c, C);
    // PRT(%-.3c, C);
    // PRT(%-.4c, C);
    // PRT(%-.5c, C);
    // PRT(%-.6c, C);
    printf("=====================================================\n");
    printf("flag : - / Width : X / precision : wildcard\n");
    printf("undefined behavier\n");
    // PRT_W(%-.*c, 0, C);
    // PRT_W(%-.*c, 1, C);
    // PRT_W(%-.*c, 2, C);
    // PRT_W(%-.*c, 3, C);
    // PRT_W(%-.*c, 4, C);
    // PRT_W(%-.*c, 5, C);
    // PRT_W(%-.*c, 6, C);
    // PRT_W(%-.*c, -1, C);
    // PRT_W(%-.*c, -2, C);
    // PRT_W(%-.*c, -3, C);
    // PRT_W(%-.*c, -4, C);
    // PRT_W(%-.*c, -5, C);
    // PRT_W(%-.*c, -6, C);
    printf("=====================================================\n");
    printf("flag : - / Width : number / precision : X\n");
    // PRT(%-0c, C);
    PRT(%-1c, C);
    PRT(%-2c, C);
    PRT(%-3c, C);
    PRT(%-4c, C);
    PRT(%-5c, C);
    PRT(%-6c, C);

    printf("=====================================================\n");
    printf("flag : - / Width : number / precision : number\n");
    printf("undefined behavier\n");
    PRT(%-2.c, C);
    // PRT(%-2.0c, C);
    // PRT(%-2.3c, C);
    // PRT(%-2.4c, C);
    // PRT(%-3.2c, C);
    // PRT(%-3.3c, C);
    // PRT(%-3.4c, C);
    // PRT(%-4.3c, C);
    // PRT(%-4.4c, C);
    // PRT(%-4.5c, C);

    printf("=====================================================\n");
    printf("flag : - / Width : number / precision : wildcard\n");
    printf("undefined behavier\n");
    // PRT_W(%-2.*c, 0, C);
    // PRT_W(%-2.*c, 3, C);
    // PRT_W(%-2.*c, 4, C);
    // PRT_W(%-2.*c, -1, C);
    // PRT_W(%-2.*c, -2, C);
    // PRT_W(%-2.*c, -3, C);
    // PRT_W(%-2.*c, -4, C);
    // PRT_W(%-3.*c, 2, C);
    // PRT_W(%-3.*c, 3, C);
    // PRT_W(%-3.*c, 4, C);
    // PRT_W(%-3.*c, -4, C);
    // PRT_W(%-4.*c, 0, C);
    // PRT_W(%-4.*c, -1, C);
    // PRT_W(%-4.*c, 4, C);
    // PRT_W(%-4.*c, 5, C);
    // PRT_W(%-4.*c, -5, C);

    printf("=====================================================\n");
    printf("flag : - / Width : wildcard / precision : X\n");
    PRT_W(%-*c, 0, C);
    PRT_W(%-*c, 1, C);
    PRT_W(%-*c, 2, C);
    PRT_W(%-*c, 3, C);
    PRT_W(%-*c, 4, C);
    PRT_W(%-*c, 5, C);
    PRT_W(%-*c, 6, C);
    PRT_W(%-*c, -1, C);
    PRT_W(%-*c, -2, C);
    PRT_W(%-*c, -3, C);
    PRT_W(%-*c, -4, C);
    PRT_W(%-*c, -5, C);
    PRT_W(%-*c, -6, C);

    printf("=====================================================\n");
    printf("flag : - / Width : wildcard / precision : number\n");
    printf("undefined behavier\n");
    PRT_W(%-*.c, 0, C);
    // PRT_W(%-*.0c, 1, C);
    // PRT_W(%-*.4c, 2, C);
    // PRT_W(%-*.1c, 3, C);
    // PRT_W(%-*.5c, 4, C);
    // PRT_W(%-*.1c, 5, C);
    // PRT_W(%-*.6c, 6, C);
    // PRT_W(%-*.0c, -1, C);
    // PRT_W(%-*.4c, -2, C);
    // PRT_W(%-*.3c, -3, C);
    // PRT_W(%-*.3c, -4, C);
    // PRT_W(%-*.3c, 4, C);
    // PRT_W(%-*.5c, 3, C);

    printf("=====================================================\n");
    printf("flag : - / Width : wildcard / precision : wildcard\n");
	printf("undefined behavier\n");
    // PRT_WW(%-*.*c, 0, 0, C);
    // PRT_WW(%-*.*c, 1, 0, C);
    // PRT_WW(%-*.*c, 2, 4, C);
    // PRT_WW(%-*.*c, 3, 1, C);
    // PRT_WW(%-*.*c, 4, 5, C);
    // PRT_WW(%-*.*c, 5, 1, C);
    // PRT_WW(%-*.*c, 6, 6, C);
    // PRT_WW(%-*.*c, -1, 0, C);
    // PRT_WW(%-*.*c, -2, 4, C);
    // PRT_WW(%-*.*c, -3, 3, C);
    // PRT_WW(%-*.*c, -4, 3, C);
    // PRT_WW(%-*.*c, 4, 3, C);
    // PRT_WW(%-*.*c, 3, 5, C);
    // PRT_WW(%-*.*c, 2, -4, C);
    // PRT_WW(%-*.*c, 3, -1, C);
    // PRT_WW(%-*.*c, 4, -5, C);
    // PRT_WW(%-*.*c, 5, -1, C);
    // PRT_WW(%-*.*c, 6, -6, C);
    printf("=====================================================\n");
}
